# Generated by Django 3.0.6 on 2020-05-12 20:46

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encampment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('recorded_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('supplies_delivered', models.TextField(blank=True)),
                ('food_delivered', models.TextField(blank=True)),
                ('occupancy', django.contrib.postgres.fields.ranges.IntegerRangeField(null=True)),
                ('talked_to', models.IntegerField()),
                ('assessed', models.IntegerField()),
                ('assessed_asymptomatic', models.IntegerField()),
                ('needs', models.TextField()),
                ('notes', models.TextField()),
                ('encampment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Encampment')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('encampment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Encampment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
