# Generated by Django 3.0.6 on 2020-05-13 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledvisit',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting.ScheduledVisit'),
        ),
    ]
