# Generated by Django 3.0.6 on 2020-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encampment',
            old_name='canonical_location',
            new_name='location_geom',
        ),
        migrations.AddField(
            model_name='encampment',
            name='location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
