# Generated by Django 3.0.6 on 2020-05-20 14:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0004_auto_20200520_1404"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encampment",
            name="location",
            field=models.TextField(
                help_text="An intersection or address. Adding a city/state can help accuracy."
            ),
        ),
        migrations.AlterField(
            model_name="encampment",
            name="name",
            field=models.TextField(
                help_text="A descriptive name for the encampment, which may be based on the address."
            ),
        ),
    ]
