# Generated by Django 3.0.6 on 2020-05-22 15:06
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0006_auto_20200520_1458"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="encampment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="reporting.Encampment",
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=512)),
                ("details", models.TextField(blank=True)),
                ("completed", models.DateField(null=True)),
                (
                    "encampment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="reporting.Encampment",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
