# Generated by Django 3.0.6 on 2020-05-25 13:24
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reporting", "0007_auto_20200522_1506"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="task", name="completed", field=models.DateTimeField(null=True),
        ),
    ]
