# Generated by Django 3.0.6 on 2020-05-25 14:16
from django.db import migrations
from django.db import models
from django.utils.text import slugify


def migrate_forward(apps, schema_editor):
    Region = apps.get_model("reporting", "Region")
    for region in Region.objects.all():
        region.slug = slugify(region.name)
        region.save()
        print("Generated slug for {}: {}".format(region, region.slug))


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0008_auto_20200525_1324"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_forward, migrations.RunPython.noop,),
    ]
