# Generated by Django 3.0.6 on 2020-05-26 03:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0009_region_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="encampment", options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(name="region", options={"ordering": ("name",)},),
        migrations.AddField(
            model_name="report",
            name="education_provided",
            field=models.CharField(default="Verbal", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="report",
            name="type_of_setup",
            field=models.CharField(default="Tents", max_length=100),
            preserve_default=False,
        ),
    ]
