# Generated by Django 3.0.6 on 2020-05-29 13:13
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0010_auto_20200526_0325"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledvisit",
            name="organization",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.Organization",
            ),
            preserve_default=False,
        ),
    ]
