# Generated by Django 3.0.6 on 2020-05-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_scheduledvisit_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='occupancy',
            field=models.CharField(choices=[('xs', '0-5'), ('s', '5-10'), ('m', '10-20'), ('l', '20-50'), ('xl', '50+')], max_length=20, null=True, verbose_name='People Living Here'),
        ),
    ]
