# Generated by Django 3.0.6 on 2020-05-29 18:07
import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0012_auto_20200529_1711"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encampment",
            name="location_geom",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="report",
            name="assessed",
            field=models.IntegerField(verbose_name="People Assessed for COVID"),
        ),
        migrations.AlterField(
            model_name="report",
            name="assessed_asymptomatic",
            field=models.IntegerField(
                verbose_name="People Assessed for COVID and Asymptomatic"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="date",
            field=models.DateField(verbose_name="Date Visited"),
        ),
        migrations.AlterField(
            model_name="report",
            name="education_provided",
            field=models.CharField(
                max_length=100, verbose_name="COVID Education Provided"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="food_delivered",
            field=models.TextField(blank=True, help_text="Specify items & quantity"),
        ),
        migrations.AlterField(
            model_name="report",
            name="needs",
            field=models.TextField(blank=True, verbose_name="Outstanding Needs"),
        ),
        migrations.AlterField(
            model_name="report",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Other Notes"),
        ),
        migrations.AlterField(
            model_name="report",
            name="performed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reporting.Organization",
                verbose_name="Visiting Organization",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="supplies_delivered",
            field=models.TextField(blank=True, help_text="Specify items & quantity"),
        ),
        migrations.AlterField(
            model_name="report",
            name="talked_to",
            field=models.IntegerField(verbose_name="People Talked To"),
        ),
        migrations.AlterField(
            model_name="report",
            name="type_of_setup",
            field=models.CharField(help_text="Tents, vehicles, etc.", max_length=100),
        ),
    ]
